WRONG_PASSWORD_OR_LOGIN = 'Неверный пароль или логин'
USER_EXISTS = 'Пользователь с таким password или email уже используется'
USER_CREATED = 'Пользователь успешно создан'
CODE_SENT_TO_MAIL = 'На электронную почту отправлен код'
WRONG_CODE = 'Неверный код подтверждения'
TIME_EXPIRED = 'Время действия кода вышло. Повторите запрос'
