repos:

- repo: https://github.com/ambv/black
  rev: 23.3.0
  hooks:
    - id: black
      exclude: (migrations|settings|README.md)
      args: [ --line-length=120, --skip-string-normalization]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: README.md
    -   id: check-added-large-files
        exclude: README.md
    -   id: check-yaml
        exclude: README.md
    -   id: check-case-conflict
        exclude: README.md
    -   id: check-merge-conflict
        exclude: README.md
    -   id: double-quote-string-fixer
        exclude: README.md
    -   id: end-of-file-fixer
        exclude: README.md

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort
      exclude: (migrations)
      args: [--profile, black, --known-local-folder, users, api]

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      args: [--max-line-length=120]
      exclude: (migrations|settings|README.md)
