repos:

- repo: https://github.com/ambv/black
  rev: 23.3.0
  hooks:
    - id: black
      exclude: (migrations|settings)
      args: [ --line-length=120, --skip-string-normalization]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort
      exclude: (migrations)
      # args: [--profile, black, --known-local-folder, users, api, backend]
      args: [--profile, black, --project, users, api, backend]
      # args: [--profile, black, -src-path, backend]

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      args: [--max-line-length=120]
      exclude: (migrations|settings|tests)
